/**
 * This file is GENERATED by `npm run generate:api` from the FastAPI `/openapi.json`.
 *
 * Do NOT hand-edit beyond this placeholder. CI regenerates it by booting the API
 * and running `openapi-typescript`. Until the first CI run or a local regen, the
 * shape below is a minimal hand-written stub that mirrors `api/guidian/schemas/*`
 * just closely enough for the component library to typecheck.
 */

export type UUID = string;
export type ISODate = string;

export type LearningStyle = "visual" | "auditory" | "read" | "kinesthetic";

export interface QuizQuestion {
  id: string;
  type: "single_choice" | "multiple_choice" | "true_false";
  prompt: string;
  choices: string[];
  correct: number | number[] | boolean;
  explanation?: string | null;
}

export interface QuizPayload {
  questions: QuizQuestion[];
}

export interface Diagram {
  id: string;
  mermaid: string;
  url?: string | null;
}

export interface Lesson {
  id: UUID;
  module_id: UUID;
  title: string;
  order_index: number;
  objectives: string[];
  mdx_content: string;
  audio_url?: string | null;
  transcript?: string | null;
  diagrams: Diagram[];
  quiz: QuizPayload;
  style_tags: LearningStyle[];
  clock_minutes: number;
  requires_completion: boolean;
  version: number;
}

export interface Module {
  id: UUID;
  course_id: UUID;
  title: string;
  description?: string | null;
  order_index: number;
  lessons: Lesson[];
}

export interface Course {
  id: UUID;
  organization_id?: UUID | null;
  title: string;
  slug: string;
  description?: string | null;
  status: "draft" | "generating" | "published" | "archived";
  ceu_hours: number;
  ceu_rules: Record<string, unknown>;
  accrediting_body?: string | null;
  state_approvals: unknown[];
  version: number;
  created_at: ISODate;
  modules?: Module[];
}

export interface TokenPair {
  access_token: string;
  refresh_token: string;
  token_type: "bearer";
}

export type UserRole = "learner" | "instructor" | "admin" | "org_admin";

export interface IdentityData {
  full_name: string;
  license_number?: string | null;
  last_four_ssn?: string | null;
}

export interface UserProfile {
  identity_verified_at?: string | null;
  identity_data?: IdentityData | null;
  [key: string]: unknown;
}

export interface UserRead {
  id: UUID;
  email: string;
  full_name?: string | null;
  role: UserRole;
  is_active: boolean;
  organization_id?: UUID | null;
  created_at: ISODate;
  profile?: UserProfile | null;
}

export interface IdentityVerifyRequest {
  full_name: string;
  license_number?: string | null;
  last_four_ssn?: string | null;
}

export interface Enrollment {
  id: UUID;
  user_id: UUID;
  course_id: UUID;
  status: "active" | "completed" | "expired";
  started_at: ISODate;
  completed_at?: ISODate | null;
  progress_pct: number;
}

export interface LessonProgressRead {
  id: UUID;
  user_id: UUID;
  lesson_id: UUID;
  seconds_spent: number;
  variant_served?: LearningStyle | null;
  completed: boolean;
  completed_at?: ISODate | null;
  behavioral_signals: Record<string, unknown>;
}

export interface LessonProgressUpdate {
  seconds_spent?: number;
  variant_served?: LearningStyle;
  completed?: boolean;
  behavioral_signals?: Record<string, unknown>;
}

export interface LearnerProfile {
  id: UUID;
  user_id: UUID;
  vark_scores: Partial<Record<LearningStyle, number>>;
  style_vector: number[] | null;
  preferences: Record<string, unknown>;
  preferred_style: LearningStyle;
  created_at: ISODate;
  updated_at: ISODate;
}

export interface VARKAnswer {
  question_id: string;
  style: LearningStyle;
}

export interface VARKSubmission {
  answers: VARKAnswer[];
}

export interface BehavioralSignal {
  lesson_id?: UUID;
  variant: LearningStyle;
  event: "dwell" | "switch" | "replay";
  seconds?: number;
}

export interface BehavioralSignalBatch {
  signals: BehavioralSignal[];
}

// --- Quiz ---
export type QuizAnswer = number | number[] | boolean;

export interface QuizAttemptRequest {
  answers: Record<string, QuizAnswer>;
}

export interface QuestionResult {
  question_id: string;
  correct: boolean;
  explanation?: string | null;
  correct_answer?: QuizAnswer | null;
}

export interface QuizAttemptRead {
  id: UUID;
  user_id: UUID;
  lesson_id: UUID;
  score: number;
  passed: boolean;
  created_at: ISODate;
  per_question: QuestionResult[];
}

export interface QuizAttemptsSummary {
  best_score: number;
  passed: boolean;
  attempt_count: number;
  min_passing_score: number;
}

// --- Compliance ---
export type ComplianceCheckStatus = "passed" | "failed" | "pending" | "not_applicable";

export interface ComplianceCheck {
  id: string;
  label: string;
  status: ComplianceCheckStatus;
  detail?: string | null;
}

export interface ComplianceDecision {
  user_id: UUID;
  course_id: UUID;
  eligible: boolean;
  ceu_hours_awarded: number;
  certificate_valid_days?: number | null;
  min_passing_score: number;
  min_clock_minutes: number;
  requires_proctoring: boolean;
  requires_identity_verification: boolean;
  state_approvals: Array<Record<string, unknown>>;
  accrediting_body?: string | null;
  checks: ComplianceCheck[];
  blockers: string[];
}

// --- Certificates ---
export type CertificateStatus = "pending" | "issued" | "failed";

export interface CertificateRead {
  id: UUID;
  user_id: UUID;
  course_id: UUID;
  ceu_hours: number;
  issued_at: ISODate;
  expires_at?: ISODate | null;
  verification_code: string;
  pdf_url?: string | null;
  status: CertificateStatus;
  download_url?: string | null;
}

// --- xAPI ---
export interface XAPIActor {
  objectType?: string;
  name?: string;
  mbox?: string;
}
export interface XAPIVerb {
  id: string;
  display: Record<string, string>;
}
export interface XAPIActivityDefinition {
  name?: Record<string, string>;
  description?: Record<string, string>;
  type?: string;
  extensions?: Record<string, unknown>;
}
export interface XAPIActivity {
  objectType?: string;
  id: string;
  definition?: XAPIActivityDefinition;
}
export interface XAPIResult {
  completion?: boolean;
  success?: boolean;
  score?: { scaled?: number; raw?: number; min?: number; max?: number };
  duration?: string;
  extensions?: Record<string, unknown>;
}
export interface XAPIStatementRead {
  id: UUID;
  stored_at: ISODate;
  actor: XAPIActor;
  verb: XAPIVerb;
  object: XAPIActivity;
  result?: XAPIResult | null;
  context?: Record<string, unknown> | null;
}

// --- Admin ---
export interface AdminMetrics {
  users_total: number;
  learners_total: number;
  courses_total: number;
  courses_published: number;
  enrollments_total: number;
  certificates_issued: number;
  ai_jobs_pending: number;
  ai_jobs_failed: number;
  audit_events_24h: number;
}

export interface AuditLogRead {
  id: UUID;
  created_at: ISODate;
  actor_user_id?: UUID | null;
  subject_user_id?: UUID | null;
  course_id?: UUID | null;
  event_type: string;
  payload: Record<string, unknown>;
}

export interface AIJobRead {
  id: UUID;
  status: string;
  course_id?: UUID | null;
  requested_by?: UUID | null;
  prompt: string;
  error?: string | null;
  attempts: number;
  created_at: ISODate;
  updated_at: ISODate;
}

export interface CEURuleRead {
  id: UUID;
  course_id: UUID;
  total_ceu_hours: number;
  min_passing_score: number;
  requires_proctoring: boolean;
  requires_identity_verification: boolean;
  state_approvals: unknown[];
  accrediting_body?: string | null;
  min_clock_minutes: number;
  certificate_valid_days?: number | null;
  created_at: ISODate;
}

export interface CEURuleCreate {
  course_id: UUID;
  total_ceu_hours: number;
  min_passing_score?: number;
  requires_proctoring?: boolean;
  requires_identity_verification?: boolean;
  state_approvals?: Array<Record<string, unknown>>;
  accrediting_body?: string | null;
  min_clock_minutes?: number;
  certificate_valid_days?: number | null;
}

export interface CEURuleUpdate {
  total_ceu_hours?: number;
  min_passing_score?: number;
  requires_proctoring?: boolean;
  requires_identity_verification?: boolean;
  state_approvals?: Array<Record<string, unknown>>;
  accrediting_body?: string | null;
  min_clock_minutes?: number;
  certificate_valid_days?: number | null;
}

export interface CourseGenerationRequest {
  prompt: string;
  target_audience?: string;
  compliance_requirement?: string;
  ceu_hours?: number;
  num_modules?: number;
  lessons_per_module?: number;
  accrediting_body?: string;
}

export interface GenerationJobRead {
  id: UUID;
  status: string;
  course_id?: UUID | null;
  error?: string | null;
  attempts: number;
  created_at: ISODate;
}

// --- Opportunities (ROI Pipeline) ---
export interface OpportunityRead {
  id: UUID;
  title: string;
  profession: string;
  target_states: string[];
  ceu_hours: number;
  estimated_license_holders: number;
  renewal_frequency_years: number;
  avg_price_per_hour: number;
  competition_level: "low" | "medium" | "high";
  content_reuse_score: number;
  status: "pipeline" | "in_progress" | "published" | "skipped";
  course_id?: UUID | null;
  notes?: string | null;
  created_at: ISODate;
  updated_at: ISODate;
  annual_addressable_market: number;
  roi_score: number;
}

export interface OpportunityUpdate {
  status?: string;
  notes?: string | null;
  course_id?: UUID | null;
  competition_level?: string;
  content_reuse_score?: number;
}

// --- State Requirements + Compliance Submissions ---
export interface StateRequirementRead {
  id: UUID;
  state_code: string;
  profession: string;
  regulatory_body: string;
  regulatory_url: string;
  provider_app_url?: string | null;
  course_app_url?: string | null;
  application_fee?: number | null;
  renewal_period_years: number;
  online_allowed: boolean;
  proctoring_required: boolean;
  min_passing_score: number;
  min_seat_time_minutes?: number | null;
  submission_format: string;
  processing_days: number;
  notes?: string | null;
}

export interface SubmissionRead {
  id: UUID;
  course_id: UUID;
  state_code: string;
  profession: string;
  status: string;
  submitted_at?: ISODate | null;
  approved_at?: ISODate | null;
  expires_at?: ISODate | null;
  approval_number?: string | null;
  notes?: string | null;
  created_at: ISODate;
  updated_at: ISODate;
  course_title?: string | null;
}

export interface SubmissionCreate {
  course_id: UUID;
  state_code: string;
  profession: string;
  notes?: string | null;
}

export interface SubmissionUpdate {
  status?: string;
  approval_number?: string | null;
  notes?: string | null;
  submitted_at?: ISODate | null;
  approved_at?: ISODate | null;
  expires_at?: ISODate | null;
}

// --- AI Teacher ---
export interface LearnerMemoryRead {
  profession: string | null;
  license_state: string | null;
  license_type: string | null;
  renewal_deadline: string | null;
  long_term_summary: string | null;
  strengths: string[];
  struggle_areas: string[];
  learning_goals: string | null;
  onboarding_complete: boolean;
  vark_style: string | null;
  total_sessions: number;
  last_session_at: string | null;
}
