"""
Curated reference diagram URLs for home inspection course topics.

Each entry maps a set of topic keywords to a self-hosted R2 URL.
Generated by scripts/seed_diagram_references.py — do not edit by hand.
"""
from __future__ import annotations

# keyword → R2 reference image URL
_REFERENCE_MAP: list[tuple[tuple[str, ...], str]] = [
    (('electrical panel', 'breaker', 'load center', 'service panel'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/reference-diagrams/electrical/panel.jpg'),
]


def find_reference_url(title: str, objectives: list[str]) -> str | None:
    """
    Given a lesson title and objectives, return a reference diagram URL
    if a curated match exists. Returns None if no match found.
    """
    search_text = " ".join([title.lower()] + [o.lower() for o in objectives])
    for keywords, url in _REFERENCE_MAP:
        if any(kw in search_text for kw in keywords):
            return url
    return None
