"""
Curated reference diagram URLs for home inspection course topics.

Each entry maps a set of topic keywords to a self-hosted R2 URL.
Generated by scripts/generate_diagram_library.py — do not edit by hand.
"""
from __future__ import annotations

# keyword → R2 reference image URL
_REFERENCE_MAP: list[tuple[tuple[str, ...], str]] = [
    (('wood framing', 'stud wall', 'header', 'king stud', 'wall framing', 'cripple stud'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/structural/wall-framing.png'),
    (('floor joist', 'floor framing', 'subfloor', 'sill plate', 'floor beam'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/structural/floor-joist-system.png'),
    (('rafter', 'ridge board', 'bird mouth', 'collar tie', 'roof framing', 'rafter tail'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/structural/roof-rafter-framing.png'),
    (('load path', 'gravity load', 'structural load', 'force transfer', 'load bearing'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/structural/load-path.png'),
    (('foundation type', 'slab on grade', 'crawlspace foundation', 'basement foundation', 'stem wall'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/structural/foundation-types.png'),
    (('crawl space', 'crawlspace', 'vapor barrier', 'pier', 'girder', 'crawlspace ventilation'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/structural/crawlspace-anatomy.png'),
    (('beam connection', 'post beam', 'beam to post', 'structural connection', 'hold down'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/structural/beam-connections.png'),
    (('cantilever', 'cantilevered floor', 'bay window framing', 'cantilever joist'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/structural/cantilever-framing.png'),
    (('asphalt shingle', 'shingle installation', 'roof shingle', 'underlayment', 'ice and water shield'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/roofing/roof-shingle-layers.png'),
    (('step flashing', 'roof to wall', 'sidewall flashing', 'counterflashing'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/roofing/step-flashing-detail.png'),
    (('roof valley', 'valley flashing', 'open valley', 'closed valley', 'woven valley'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/roofing/valley-flashing-types.png'),
    (('chimney flashing', 'chimney cricket', 'saddle flashing', 'chimney counterflashing'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/roofing/chimney-flashing-detail.png'),
    (('roof drainage', 'gutter downspout', 'roof runoff', 'drainage path', 'splash block'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/roofing/roof-drainage-hierarchy.png'),
    (('gutter installation', 'gutter slope', 'drip edge', 'gutter hanger', 'fascia gutter'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/roofing/gutter-installation.png'),
    (('ice dam', 'ice damming', 'roof ice', 'freeze thaw roof', 'eave ice'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/roofing/ice-dam-formation.png'),
    (('roof vent', 'ridge vent', 'power vent', 'turbine vent', 'box vent', 'roof ventilation type'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/roofing/roof-ventilation-types.png'),
    (('fascia', 'soffit', 'frieze board', 'eave detail', 'soffit vent'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/roofing/fascia-soffit-detail.png'),
    (('service entrance', 'service drop', 'weatherhead', 'meter socket', 'service conductor'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/electrical/service-entrance-panel.png'),
    (('electrical panel', 'breaker panel', 'load center', 'circuit breaker', 'service panel', 'bus bar'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/electrical/circuit-breaker-panel.png'),
    (('gfci', 'ground fault', 'gfci outlet', 'gfci wiring', 'gfci protection', 'load terminal'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/electrical/gfci-outlet-wiring.png'),
    (('branch circuit', 'circuit wiring', 'wire color', 'hot neutral ground', 'circuit path'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/electrical/branch-circuit-diagram.png'),
    (('electrical defect', 'double tapped', 'aluminum wiring hazard', 'ungrounded outlet', 'reversed polarity', 'electrical hazard'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/electrical/electrical-defects-checklist.png'),
    (('aluminum wiring', 'AL wiring', 'aluminum conductor', 'aluminum wire hazard'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/electrical/aluminum-wiring-identification.png'),
    (('grounding electrode', 'ground rod', 'water pipe ground', 'grounding system', 'GEC'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/electrical/whole-house-grounding.png'),
    (('knob and tube', 'knob tube', 'old wiring', 'ceramic knob', 'ceramic tube', 'cloth wiring'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/electrical/knob-tube-wiring.png'),
    (('drain waste vent', 'DWV', 'plumbing vent', 'soil stack', 'branch drain', 'cleanout'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/plumbing/dwv-system.png'),
    (('p trap', 'drain trap', 'trap seal', 'trap arm', 'sewer gas', 'plumbing trap'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/plumbing/p-trap-function.png'),
    (('water heater', 'anode rod', 'dip tube', 'T&P valve', 'water heater components', 'gas water heater'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/plumbing/water-heater-anatomy.png'),
    (('water supply', 'supply system', 'pressure reducing valve', 'main shutoff', 'water distribution'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/plumbing/supply-system.png'),
    (('T&P valve', 'temperature pressure relief', 'relief valve', 'TPR valve', 'water heater safety'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/plumbing/water-heater-tpr-valve.png'),
    (('water meter', 'main shutoff valve', 'water service', 'curb stop', 'ball valve shutoff'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/plumbing/water-meter-shutoff.png'),
    (('drain slope', 'pipe slope', 'drain pitch', '1/4 inch per foot', 'horizontal drain grade'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/plumbing/drain-slope-requirements.png'),
    (('air admittance valve', 'AAV', 'wet vent', 'plumbing vent types', 'island vent', 'vent stack'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/plumbing/plumbing-vent-types.png'),
    (('forced air', 'hvac ductwork', 'supply duct', 'return air', 'furnace', 'air handler'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/hvac/forced-air-system.png'),
    (('heat pump', 'refrigerant cycle', 'compressor', 'condenser', 'evaporator', 'heat pump cycle'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/hvac/heat-pump-refrigerant-cycle.png'),
    (('combustion air', 'confined space', 'gas appliance', 'combustion air opening', 'direct vent'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/hvac/combustion-air-requirements.png'),
    (('attic ventilation', 'soffit vent', 'ridge vent', 'attic airflow', 'net free area'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/hvac/attic-ventilation.png'),
    (('air handler', 'blower motor', 'evaporator coil', 'heat strip', 'air handler components', 'furnace components'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/hvac/air-handler-components.png'),
    (('duct system', 'flex duct', 'sheet metal duct', 'duct board', 'duct leakage', 'duct type'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/hvac/duct-system-types.png'),
    (('vapor barrier', 'vapor retarder', 'vapor barrier placement', 'climate zone insulation', 'wall vapor'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/moisture/vapor-barrier-placement.png'),
    (('insulation type', 'batt insulation', 'blown insulation', 'rigid foam', 'spray foam', 'R-value comparison'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/moisture/insulation-types-comparison.png'),
    (('moisture intrusion', 'water infiltration', 'moisture path', 'building envelope moisture', 'water entry'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/moisture/moisture-intrusion-paths.png'),
    (('window flashing', 'window rough opening', 'pan flashing', 'WRB', 'window installation detail'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/moisture/window-installation-flashing.png'),
    (('deck ledger', 'ledger board', 'deck attachment', 'ledger flashing', 'deck to house connection'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/moisture/deck-ledger-connection.png'),
    (('smoke detector', 'CO detector', 'carbon monoxide', 'smoke alarm placement', 'detector location'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/safety/smoke-co-detector-placement.png'),
    (('egress window', 'bedroom egress', 'window egress', 'egress opening', 'egress requirements'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/safety/egress-window-requirements.png'),
    (('stair code', 'riser height', 'tread depth', 'handrail', 'stair requirements', 'stairway'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/safety/stair-requirements.png'),
    (('deck guardrail', 'baluster spacing', 'guardrail height', 'deck railing', 'guardrail code'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/safety/deck-guardrail-code.png'),
    (('garage fire separation', 'garage to house', 'fire wall garage', 'garage door rating', 'attached garage'), 'https://797358481bc7dd22f58621e9713eccd3.r2.cloudflarestorage.com/guidian-courses/diagrams/safety/garage-fire-separation.png'),
]


def find_reference_url(title: str, objectives: list[str]) -> str | None:
    """
    Given a lesson title and objectives, return a reference diagram URL
    if a curated match exists. Returns None if no match found.
    """
    search_text = " ".join([title.lower()] + [o.lower() for o in objectives])
    for keywords, url in _REFERENCE_MAP:
        if any(kw in search_text for kw in keywords):
            return url
    return None
